### PR TITLE
Refactor codebase.split the code into different different files and f…

### PR DESCRIPTION
**Pull request by gtlYashParmar**
# Pull Request Summary:

## Purpose:
This pull request, in response to issue #33, addresses a critical need for codebase refactoring. The primary objective is to enhance the overall structure and maintainability of the project.

## Changes Made:
In this pull request, we have undertaken a significant refactoring effort. Prior to this, the entire codebase was contained within a single monolithic file (main.py). The key changes introduced are as follows:

- **Modularization:** We have divided the codebase into separate, logically organized modules. These include `actions`, `config`, `dialogs`, `exceptions`, `prompts`, and `utils`.

- **Utility Functions:** Within the newly created `utils` module, we have introduced utility functions to aid in various aspects of the codebase. This includes functions such as `prompt_util`, `ansi_colors`,`screenshot_util` and `action_util`.

## Impact of Changes:
The ramifications of these changes extend beyond immediate enhancements. The objectives are multi-fold:

- **Improved Navigability:** The modularization ensures that the codebase is more navigable and comprehensible, fostering efficient development and maintenance.

- **Foundation for Future Development:** This refactoring serves as a solid foundation for future feature development and bug fixes, making the project more adaptable and scalable.

## Testing Done:
To validate the integrity of this refactoring, comprehensive manual testing has been conducted. The testing process covered all functionalities to ensure that they continue to perform as expected. This rigorous testing regimen aimed to identify and mitigate any potential regressions introduced during the refactoring process.

## Call to Action:
Feedback on the new structure, especially with regard to naming conventions and the modularization approach, is highly appreciated.

### CODE REVIEW

**Comment by joshbickett** [comment]
@gtlYashParmar Thank you for the PR. It looks good at a high level, but I'll dive deeper and let you know if I have any questions

**Comment by joshbickett** [comment]
@gtlYashParmar nice job with this refactor. It passed my tests. I'll merge in. I have a little more feedback I'll share shortly.

**Comment by Yash-1511** [comment]
Thank you, @joshbickett. This is @gtlYashParmar, reaching out from my main account. I'm about to submit a feature enhancement related to running this application via Docker container. I'll detail this in an upcoming issue and would appreciate your feedback on it.

**Comment by joshbickett** [comment]
@Yash-1511 The additional thought I had on this PR was , what do you think about changing the name of `/actions` to `/models`

**Comment by Yash-1511** [comment]
@joshbickett Renaming the section to `models` seems feasible. Additionally, we've incorporated several functions dedicated to actions, which include tasks such as performing specific operations, validation, and summarization. If you agree, we can proceed with this modification. I also suggest that `actions` might be a more descriptive and suitable name than `models` for the section related to interactive functionalities.

**Pull request merged**
