### PR TITLE
Voice functionality added with Whisper

### PR DESCRIPTION
**Pull request by younesbram**
Added voice functionality with whisper. Implemented a `--voice` command-line flag using `argparse`.

### CODE REVIEW

**Comment by joshbickett** [comment]
@younesbram I'm excited for this PR, but I ran into an issue installing `whisper-mic`. It sounds like it may be resolvable with `brew install portaudio`, but my concern is about adding another install statement for the overall project for it to use voice which may not be used by all users. 

I created a ChatGPT thread with the context here: https://chat.openai.com/share/0446a868-42f8-469e-953d-394bf21e9ad0

Do you know a better solution that doesn't require `brew install portaudio`?

**Comment by joshbickett** [comment]
If there's some way to only require `brew install portaudio` if the user is doing voice, that could be good, but right now I think it will break for all users on `pip install -r requirements.txt` if they do not have `portaudio`

**Comment by younesbram** [comment]
I don't have the issue when installing, I think its a mac thing. Wish my macbook wasn't broken else Id test on that too.

 I tried it with wsl and gitbash and normal cmd. Will try to debug right now and investigate for any solutions to seamlessly not break installation for mac users who are using voice.

**Comment by younesbram** [comment]
image
Many options to choose from!
I personally like adding the troubleshooting in the documentation. First place people go to after a bug is the same github repo they got it from.

**Comment by joshbickett** [comment]
I think I like `1 conditional requirement` most. My concern with `2 documentation` is it sounds like all mac users will see a red fail on `pip install -r requirements.txt`. If they ignore and don't use mic then it sounds like it will work fine. Most will probably feel like they need to troubleshoot it even if they technically don't. Let me know if I am understanding this correctly. 

I like `1 conditional requirement` because it sounds like it wouldn't add any installation steps for the dev on the `readme.md`. That's really my goal, not to add another step. If we could add a conditional install that'd be great, but I'm not aware if that's possible with `brew install portaudio`. As far as I'm aware I've never used `pip` to start a `brew install` command, but honestly I don't know what's possible here. If you could figure it out and resolve, I'll look at the PR again and see if it works for me, Thanks!

**Comment by younesbram** [comment]
Thing is.. if its breaking for users in the pip install -r requirements.txt part (step 5), the only valid solution is to add another step to install for voice users only. This will also be a chance to say run ``` operate --voice ``` as a final step. I tried doing the markers thing but you were right, the package cannot be installed with pip needs  (apt or brew)

**Comment by joshbickett** [comment]
Oh I just realized the ChatGPT share link is not updating with new information for some reason. Here's the update for context.

__
You're correct in identifying the challenge of requiring all users to install additional dependencies, especially when it's only needed for a specific feature. However, there are a few strategies you could use to handle this situation more gracefully:

Optional Dependencies: Modify your requirements.txt to only include essential packages. Then, provide a separate requirements-audio.txt for the with-audio feature, which includes PyAudio and its dependencies. In your documentation, instruct users who want to use the with-audio feature to run an additional command, like:

```
pip install -r requirements-audio.txt
```

**Comment by joshbickett** [comment]
Ok, just finished looking at it. It is merged. Thanks for all your help with this. If you want to make updates to the voice and accessibility features overtime that'd be great!

**Comment by joshbickett** [comment]
Actually there may have been an issue for users not using `--voice`. I reverted the commit because when I did a fresh install I was getting an import issue

**Comment by younesbram** [comment]
will checkSent from my iPhoneOn Dec 5, 2023, at 9:28 AM, Josh Bickett ***@***.***> wrote:﻿
Actually there may have been an issue for users not using --voice. I reverted the commit because when I did a fresh install I was getting an import issue

**Comment by joshbickett** [comment]
Ok, trying to fix it now

**Comment by joshbickett** [comment]
@younesbram so I'm not that good at `git reverts`. I reverted and made the following fix: https://github.com/OthersideAI/self-operating-computer/commit/b011fa84edbc5567b31e8fb6d5e86abdb55d6764

The problem is I then went to push back to `main` but was having an issue and somehow lost your recent commits. Anyway, voice is merged back in `main` and appears to me working without causing issued of devs that don't use it! :)

**Comment by joshbickett** [comment]
@Siddhant-Goswami oh. Thanks for letting us know. Could you submit an issue ticket for this if you haven't already?

**Comment by younesbram** [comment]
@Siddhant-Goswami hello friend. seems like an environment issue, try reloading with a new env. i will check on my mac VM with your version of ventura soon

**Pull request merged**
