### PR TITLE
Add scrolling support and replace CLICK action

### LINKED ISSUE #74: Scrolling up and down not added
I just noticed that the model doesn't have access to scrolling up and down. Is this difficult to implement generally (asking mostly for Linux, but of course interested in Mac, and Windows)?

If so, I may try adding in a web mode and leverage Selenium to scroll.

### PR DESCRIPTION
**Pull request by michaelhhogue**
**This PR aims to achieve two primary objectives:**

1. Support vertical mouse-wheel scrolling to let the model access UI elements which currently aren't on the screen. 

2. Replace the CLICK action with a MOUSE action. The MOUSE action will open up broader support for what the model can do with the user's cursor. 
 
Currently, a CLICK action moves the cursor to (X, Y) on screen then clicks on whatever UI element is below it.
The MOUSE action will give the model the following possible capabilities:
- Move cursor to (X, Y), but don't click [Useful for any requirements to hover or giving the model a chance to first confirm if it's on the correct target UI element].
- Move the cursor to (X, Y) and do a left-click.
- Move the cursor to (X, Y) and do a positive or negative mouse-wheel scroll.

This more generalized MOUSE action opens the possibility to let the model do more things with the mouse in the future, such as a right-click or drag.

Merging the successful completion of this PR will close #74.

I am open to any suggestions or feedback as I make these changes!

### CODE REVIEW

**Comment by michaelhhogue** [comment]
Okay I think that's a wrap. The model can now hover the cursor at a chosen location and scroll up or down. I also added a bit to the vision prompt and it seems to have drastically reduced repetition for me.

**Comment by joshbickett** [comment]
@michaelhhogue thanks for this PR. Still need to review it. I'll let you know if I have any questions!

**Comment by michaelhhogue** [comment]
@joshbickett Glad you like the concept! I totally understand if you can't merge this due to the architectural changes. I'm going to put this back to draft for now until I figure out what's causing the double clicks in your test case. It could be that I added too much to the vision prompt. I'll keep you posted!

**Comment by michaelhhogue** [comment]
@joshbickett Great to hear! I've got this on hold at the moment. Currently I'm working on a PR that replaces platform-specific screenshot methods with one platform-agnostic screenshot function using [MSS](https://python-mss.readthedocs.io/examples.html). This will also enable support for multi-monitor setups. 

I'll let you know when I'm back to working on this PR. In the mean time, feel free to add any commits here improving the architecture or fixing any issues I missed.

**Comment by michaelhhogue** [comment]
@joshbickett I've tested the common case of "go to youtube and play holiday music" multiple times and I haven't had any issues with a double click. I actually notice reduced repetition with how I modified the vision prompt. However, it never takes the straightforward path to finding the video by just submitting the search query directly into the youtube url. Instead, it always googles holiday music and tries to click on the first video link. Sometimes it can click it, sometimes it can't. I've noticed this on the main branch as well.

If you want, you could try changing the vision prompt to see if it stops doing the double click for you.

**Review by Daisuke134 — COMMENTED** [review]
Scrolling and clicking are mutually excluse. You shouldn't click in the same action as a scroll since you won't yet know what you'll click on.

Sorry, I have a question. What is the purpose of this prompt? Why do we need to separate scroll and click?

**Comment by michaelhhogue** [comment]
@Daisuke134 To prevent the model from scrolling down to some point in the page and then clicking on some random UI element without seeing it first. It should stop after scrolling, look at the screen, and determine where to actually do the click.

If scrolling and a click are done in the same action you'll have issues in sites like Wikipedia where it'll scroll down, accidentally click a link, and go to the wrong article.

**Comment by Daisuke134** [comment]
@michaelhhogue Thank you so much. I will check out the scrolling action🙇‍♂️

**Comment by joshbickett** [comment]
> mutually excluse

This makes sense now that I think of it

**Comment by joshbickett** [comment]
> Scrolling and clicking are mutually excluse. You shouldn't click in the same action as a scroll since you won't yet know what you'll click on.

This makes sense now that I think of it

**Comment by joshbickett** [comment]
> Scrolling and clicking are mutually excluse. You shouldn't click in the same action as a scroll since you won't yet know what you'll click on.

This makes sense now that I think of it. 

@michaelhhogue I'll take another look at this PR and let you know if I have any questions.

**Comment by michaelhhogue** [comment]
I'm going to go ahead and close this PR for now since the architecture has changed a lot since I opened it. I'll possibly revisit this in the future.

**Pull request closed without merging**
