### PR TITLE
Feat Containerize the application to improve cross OS compatibility

### PR DESCRIPTION
**Pull request by legendkartik45**
🚀 **PR Summary:**
Adds a Dockerfile to support containerization as part of https://github.com/OthersideAI/self-operating-computer/issues/36.

🛠️ **Changes Made:**
- Included Dockerfile for containerization.
- Used Python:3.11-slim as the base image (Considering it's lightweight and supports all libs).

🔍 **Testing:**
- Tested successful build and execution using the Dockerfile.

👩‍💻 **Next Steps:**
- Review and merge if no issues arise.

🔧 **How to Build and Run:**
1. **Build the Docker Image:**
   ```bash
   
   docker build -t your_image_name .

2. **Run the Docker Image:**
   ```bash
   
   docker run -it your_image_name

### CODE REVIEW

**Comment by joshbickett** [comment]
@legendkartik45 thanks for the PR. I don't know Docker super well. I'll take a look do some learning and let you know if I have any questions! :)

**Comment by joshbickett** [comment]
@legendkartik45 let me know your thoughts on the question above. Thanks

**Comment by tomasfernandez1212** [comment]
It's going to be challenging to get this to work in a container due to the GUI limitations. What I recommend is using a VM instead. For example, you could create one inside your own desktop or provision one through a cloud provider.

**Comment by joshbickett** [comment]
@tomasfernandez1212 that's my understanding as well

**Comment by legendkartik45** [comment]
@joshbickett @tomasfernandez1212 I believe that makes sense, let me explore running on local VM and get back.

**Comment by joshbickett** [comment]
@legendkartik45 curious if you have any findings. Thakns

**Comment by joshbickett** [comment]
Hi @legendkartik45. Let me know if you found anything on this PR. 

I'll close this PR for now until we know more. If you have any updates feel free to reopen the PR

**Pull request closed without merging**
