### PR TITLE
Added Gemini Pro Vision Support to Self Operating Computer

### PR DESCRIPTION
**Pull request by linusaltacc**
I've added support for Gemini Pro Vision to the project! To utilize this feature, simply include the command line argument `-m gemini-pro-vision`. Additionally, I've updated documentation.

### CODE REVIEW

**Comment by michaelhhogue** [comment]
@linusaltacc Was working on a similar PR, but there were a lot of issues getting a consistent response. Interested to see how it works with your implementation!

**Comment by linusaltacc** [comment]
@michaelhhogue Great to hear you were working on the support as well! I'm eager to see your implementation and explore how we can combine insights to enhance the overall solution.

**Comment by joshbickett** [comment]
@linusaltacc thanks for the PR. I'm looking forward to checking this out! Have some HyperWrite / OthersideAI priorities to get through, but will try to take a look in a day or two.

**Comment by linusaltacc** [comment]
@joshbickett  Appreciate your prompt response! Looking forward to your insights and feedback whenever you get a chance to review the PR. Cheers!

**Comment by joshbickett** [comment]
@linusaltacc had a bit of trouble getting the credentials setup, but now Gemini is working. I'll do a little more testing and let you know if I have any questions. Thanks! :)

**Comment by linusaltacc** [comment]
@joshbickett sounds good!

**Comment by joshbickett** [comment]
Getting some 500 errors, but that's Google's side of things as far as I'm aware
```
Error parsing JSON: 500 An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting
```

**Comment by joshbickett** [comment]
I noticed you added support for `-accurate` to Gemini, thank you for doing this but I went ahead and removed it. `-accurate` isn't working as expected right now and it needs an update. I don't think we should support it with new models until it is confirmed to work

**Comment by joshbickett** [comment]
@linusaltacc thanks again for the PR. I went ahead and merged it. There was one thing missing, but I didn't think it needed to hold it up. When model is gemini there should be a condition in the `summarize` function to use gemini to do it. If the user doesn't have an openai key then `summarize` will fail. If you could make a PR for that, that'd be great. 

```
def summarize(messages, objective):
    try:
      
```

Other than that there are a few other changes to make but this is a good start. I'll update the `README.md` a little to specify more detail about the different model modes.

**Comment by joshbickett** [comment]
@linusaltacc do you have a Twitter account? I am happy to mention you in a post about Gemini. Let me know if you want to share you're Twitter once the summary fix is in. You can message me at josh@othersideai.com if you prefer

**Comment by linusaltacc** [comment]
> @linusaltacc thanks again for the PR. I went ahead and merged it. There was one thing missing, but I didn't think it needed to hold it up. When model is gemini there should be a condition in the `summarize` function to use gemini to do it. If the user doesn't have an openai key then `summarize` will fail. If you could make a PR for that, that'd be great.
> 
> ```
> def summarize(messages, objective):
>     try:
>       
> ```
> 
> Other than that there are a few other changes to make but this is a good start. I'll update the `README.md` a little to specify more detail about the different model modes.

@joshbickett Yeah you are right! I'm thinking of adding `model` as argument to support different models.

```
def summarize(model, messages, objective):
```

**Pull request merged**
