### PR TITLE
Dynamic Display Settings

### PR DESCRIPTION
**Pull request by ph47s74x**
**Title**: Dynamic Display Settings

**Description**:

This pull request introduces a feature to dynamically adjust screen size settings based on the primary monitor's resolution. The purpose of this update is to enhance the user experience by automatically adapting the application to the user's current screen setup.

**Changes Made**:

1. **Screen Size Settings Initialization**:
   - A dictionary `monitor_size` is initialized with default values for width (1920) and height (1080). These values represent a common screen resolution and serve as the default setting.

2. **Dynamic Adjustment Using `screeninfo`**:
   - The script now includes a try-except block to handle dynamic screen size adjustments.
   - Using the `screeninfo` library, the script fetches details of all connected monitors.
   - It then identifies the primary monitor and updates the `monitor_size` dictionary with the primary monitor's width and height.
   - The variable `monitor_metrics` is used to store a formatted string containing the dimensions of the primary monitor.

3. **Exception Handling**:
   - In case of any exceptions (e.g., `screeninfo` not being able to fetch monitor details), the script falls back to the default monitor size values.
   - The exception is caught, and an error message is printed along with the default settings being used. This ensures that the application remains functional even if dynamic adjustment fails.

**Benefits**:
- **User Convenience**: Automatically adapts to the user's monitor settings, providing an optimized interface without manual configuration.
- **Error Handling**: Gracefully handles scenarios where automatic adjustment isn't possible, ensuring the application's stability.

**Testing**:
- The feature has been tested on multiple monitors with varying resolutions.
- Exception handling has been tested to ensure the default settings are used in case of failure.

**Further Considerations**:
- Future enhancements could include user preferences for screen size, allowing manual override of the automatic settings.

This feature aims to make the application more intuitive and responsive to the user's current hardware setup, thereby enhancing overall usability and user experience.

### CODE REVIEW

**Comment by michaelhhogue** [comment]
@ph47s74x The monitor size is already detected later when doing screenshots. The monitor_size definition at the top of the code seems to just be a default. This was added in with the addition of accurate mode and probably just needs to be removed. 

However, there are some issues with detecting the screen size in accurate mode. You might want to look into that. I'm pretty sure it doesn't consider the screen size in Mac OS and just skips Windows all together.

**Comment by ph47s74x** [comment]
@michaelhhogue 
Thanks for the response. I was just digging into the code and realized that.

**Comment by michaelhhogue** [comment]
@ph47s74x No problem! Like I said though, if you fixed the issues with accurate mode using `monitor_size` and not working on Windows, that would be awesome!

**Comment by ph47s74x** [comment]
> @ph47s74x No problem! Like I said though, if you fixed the issues with accurate mode using `monitor_size` and not working on Windows, that would be awesome!

Has there been an issue created on this?

**Pull request closed without merging**
