### PR TITLE
Added -accurate, reflective mouse click mode

### PR DESCRIPTION
**Pull request by klxu03**
Implemented -accurate, reflective mouse click mode.

If you add the -accurate tag when running operate, it will enable accurate mode. Now, whenever the model tries to click on anything, it will send another additional request to GPT giving it a chance to adjust its initial percentage guesses.

I first extract out the initial guess of where the model tries to click, and then I take a screenshot of a smaller 200 x 200 pixel rectangle around the initial guess. I then upsample the image by doubling the dimensions so it's bigger to GPT (all done in capture_mini_screenshot_with_cursor) and then ask the model to refine its guess, giving it the previous image/message as context as well as the previous X Y coordinate guess it attempted and give it a chance to add and subtract minute percentages (accurate_mode_double_check).

Locally, this configuration has significantly improved the accuracy of clicking on my desktop configuration (two monitors). Currently I've only implemented it for Linux, but if this approach is liked it can easily be adapted to other OS.

Idea could be further improved if the add_grid_to_image is further improved such that in the accurate_mode adding grid case to the mini screenshot, if instead of (25%, 25%) in the first intersection, instead it was (-3%, -5%) for example so it was just the relative percentage change. This will probably allow the model to have an easier time adding and subtracting the proper amount in the refined click.

Also I almost arbitrarily chose 200 x 200 as the rectangle size. I just noticed that on my desktop, the model would often be wrong by more than 100 pixels away, but less than 200 pixels so I just chose that as the size.

I would be happy to improve my code, or explain anything as wanted!

PS: I also added poetry support. But I can delete this and just add all of those files to .gitignore

### CODE REVIEW

**Comment by michaelhhogue** [comment]
@klxu03 Using mss for screenshots on Linux appears to be a much better solution, especially for just getting the active monitor.

**Comment by klxu03** [comment]
> @klxu03 Using mss for screenshots on Linux appears to be a much better solution, especially for just getting the active monitor.

Yeah earlier I went and just did mss, but then I noticed the clicking percentage system was configured globally so they didn't align. But if you think this is worth exploring, it's probably not bad to do a conversion (like scaling GPTs output divide by two and just adding 50% to the percentage)

**Comment by michaelhhogue** [comment]
@klxu03 Ah okay I see the removal of mss now. mss is probably the best multi-platform screenshot solution and the easiest way to just get the active monitor. So looking into the conversion in order to adopt mss could definitely help!

**Comment by klxu03** [comment]
> @klxu03 Ah okay I see the removal of mss now. mss is probably the best multi-platform screenshot solution and the easiest way to just get the active monitor. So looking into the conversion in order to adopt mss could definitely help!

Yeah makes sense, I'll probably try it another time (in a diff PR). BTW, I didn't do the most prompt engineering for the -accurate, so definitely feel free to change it. 

Curious, is my code readable enough so you can follow the logic of what is happening? Are there any glaring architectural/design choices that you guys didn't like in this PR?

**Comment by klxu03** [comment]
> Ok great. If you can push up your poetry changes I think this is ready to merge into the main project.
> 
> I think this is a good architecture. It doesn't always perform well for me, but I think we can iterate it to improve performance.
> 
> -accurate = 3, means 3 layers of scoping sounds like a good approach. We can do this with a later PR.

Awesome, sounds good! I just cleaned up the repo. Going to do a quick round of testing to make sure it all works

**Comment by joshbickett** [comment]
Ok, looks good! I'm going to merge it. Can you create a new PR for one thing I noticed? 

Can you add more "app prints" so it shows a log of click logic? Something like this below. Does that make sense?
```
[Self-Operating Computer] [Act] CLICK
[Self-Operating Computer] [Act] CLICK REFLECTION
```

**Comment by klxu03** [comment]
> Ok, looks good! I'm going to merge it. Can you create a new PR for one thing I noticed?
> 
> Can you add more "app prints" so it shows a log of click logic? Something like this below. Does that make sense?
> 
> ```
> [Self-Operating Computer] [Act] CLICK
> [Self-Operating Computer] [Act] CLICK REFLECTION
> ```

Yup! This makes sense

**Comment by joshbickett** [comment]
Also the `quick start` section in `README.MD` could you create a "additional features" section or something and add this `-accurate` flag detail?

**Pull request merged**
