### PR TITLE
Refactor Codebase for Improved Structure and Maintainability realates to #33

### PR DESCRIPTION
**Pull request by gtlYashParmar**
Purpose of the PR:
This pull request addresses issue #33  and aims to refactor the codebase to enhance its structure and maintainability.

Changes Made:

- Broke down the monolithic script into modular files.
- Organized functions into separate files based on functionality.

Impact of Changes:
The changes are intended to make the codebase more navigable and maintainable, and they lay the groundwork for future feature development and bug fixes.

Testing Done:
Manual testing was conducted to ensure that all functionalities work as expected and that the refactoring does not introduce any new bugs.

Call to Action:
Feedback on the new structure, especially with regard to naming conventions and the modularization approach, is highly appreciated.

### CODE REVIEW

**Comment by joshbickett** [comment]
@gtlYashParmar thanks for the PR. Still considering this change. In part, I liked keeping the one file `main.py` since it is so few lines of code and a "lightweight" framework, but I'll consider this change

**Review by legendkartik45 — CHANGES_REQUESTED** [review]
@gtlYashParmar  loved how you did the refactoring and made code more modular.
Can we also ensure to pickup strings from some kind of enum/constants instead of directly referring to them.

image

**Comment by alm0ra** [comment]
@legendkartik45 i did in #59

**Comment by gtlYashParmar** [comment]
@joshbickett   Thank you for taking the time to review the pull request and for considering the change. I understand your point about keeping main.py as a single lightweight file, and I appreciate your willingness to consider the refactoring.

The main reason behind breaking down the code into modular files was to enhance the codebase's maintainability and readability, especially as the project potentially grows in the future. By organizing functions into separate files based on their functionality, it becomes easier to navigate and manage the codebase, which can be particularly beneficial when new features are added or when debugging becomes necessary.

Your input is highly valuable, and I'm here to collaborate on finding the best approach that works for the project. Thanks again for considering these changes.

@legendkartik45 Thanks for the feedback! I agree that using enums/constants for strings is a good practice. It enhances code maintainability and makes it easier to handle localization if needed.

To implement this, we can create a separate module or file, let's call it constants.py, where we define all the strings as constants or enums.

**Comment by joshbickett** [comment]
@gtlYashParmar Thank you again for the PR. Sorry for the inconvenience of creating this PR and not having it merged. I am learning a lot about how to run open-source projects. I am working on the `CONTRIBUTING.md` to have clearer instructions and incorporate more of the vision: https://github.com/OthersideAI/self-operating-computer/blob/main/CONTRIBUTING.md

There's still a lot code changes and bugs to fixes to get done, if you want to submit other PRs. Eventually most the work will be [software 2.0](https://karpathy.medium.com/software-2-0-a64152b37c35)

**Pull request closed without merging**
