### PR TITLE
Actions workflow for building and uploading package to PyPi.

### PR DESCRIPTION
**Pull request by Daisuke134**
### Changes Proposed
This pull request aims to eliminate the need to run "pip install -r requirements.txt" and "pip install .", simplifying the installation process to just "pip install self-operating-computer" through the implementation of a GitHub Actions workflow for automatic package upload to PyPI. 

The specific changes include:

・Creation of .github/workflows/upload-package.yml, defining a GitHub Actions workflow for automating the package upload to PyPI.
・Setting the Python version to 3.8, considering compatibility with the current version of the project.

### Next Steps
Necessary changes to setup.py will be made in additional commits. This will facilitate an easier setup and execution process for users.

### Notes
・These changes are in response to the request listed in CONTRIBUTING.md to "Remove necessity for pip install .: I think by uploading packages to PyPi we can reduce the installation code steps by consolidating pip install -r requirements.txt and pip install .. If that's possible that'd be great."
・The changes are aimed at enhancing the usability and maintainability of the project.

### CODE REVIEW

**Comment by joshbickett** [comment]
@Daisuke134 thanks for this PR. As you were probably planning in your next steps I learned we could add the code below to `setup.py` to avoid the `pip install -r requirements.txt`. I'm going to try adding that. I thought I'd add that first since it will be required for PyPi. I'll follow up on this PR in a little

```
with open("requirements.txt") as f:
    required = f.read().splitlines()
 ```

**Comment by joshbickett** [comment]
Ok, I think I've completed the configuration on the PyPi side. I'm going to merge this PR in.

**Comment by Daisuke134** [comment]
@joshbickett Thank you so much. I will check🙇‍♂️

**Comment by joshbickett** [comment]
sg, let me know what you find @Daisuke134

**Comment by Daisuke134** [comment]
@joshbickett I finished checking and pip install worked fine. I will make new PR to change read.md. I don't have a twitter account, so you can tweet without my name. Thank you so much!!

**Comment by joshbickett** [comment]
Sounds good!

**Comment by joshbickett** [comment]
Oh I didn't even notice the numbering issue, thanks for catching that @Daisuke134

**Pull request merged**
