### PR TITLE
Replace TTF search with default ImageDraw font for grid

### PR DESCRIPTION
**Pull request by michaelhhogue**
***Problem***
While experimenting with how to improve click accuracy, I discovered that sometimes the coordinates added to the grid image looked like this:

Screenshot from 2023-12-01 12-51-51

Sometimes it would be a barely legible cursive font. I discovered that this was due to the following code:
```
# Get the path to a TrueType font included with matplotlib
font_paths = fm.findSystemFonts(fontpaths=None, fontext="ttf")
# Filter for specific font name (e.g., 'Arial.ttf')
font_path = next((path for path in font_paths if "Arial" in path), None)
if not font_path:
      if len(font_paths) > 0:
          font_path = font_paths[0]
      else:
          raise RuntimeError("No TrueType fonts found on the system.")
```

Although it is filtering for Arial, the font for the resulting grid sent to GPT-4v is non-deterministic.

***Solution***
This PR replaces searching for a TrueType font with just using the default font used by ImageDraw. In addition, the calculated font size can can be passed to ```draw.text(...)``` rather than passing a whole TTF.

This is the result:
Screenshot from 2023-12-01 12-54-12

This is the font that is now used every time the grid is drawn. Since introducing this change, I've noticed a drastic improvement in click accuracy on my system (Linux).

In addition, this will prevent the exception from not having a TrueType font installed on the system.

### CODE REVIEW

**Comment by joshbickett** [comment]
@michaelhhogue another great PR. This makes sense, but I'd like to test and confirm. I'll have an update soon!

**Comment by michaelhhogue** [comment]
@joshbickett Thank you. I got ahead of myself initially and didn't realize it was filtering for Arial. So I'm not sure how I was getting some wild non-arial fonts before. But, rather than resolving that, I figured it'd be more consistent to not search for fonts in general. Hope that makes sense.

**Comment by joshbickett** [comment]
For some reason I thought we could resize the default font, but I think that's old info. This appears to work. Merged

**Comment by joshbickett** [comment]
Curious if you've played around with the grid size to try to find an optimal size?

**Comment by michaelhhogue** [comment]
@joshbickett Yeah I've been experimenting with the grid interval. I've had pretty good luck with it at 250. However, I notice a bigger difference in adding more detail to the vision prompt. 

Most of my work right now is optimizing the grid interval in combination with the vision prompt  detail/strictness.

**Pull request merged**
