### PR TITLE
Enhanced error handling in key functions

### PR DESCRIPTION
**Pull request by Prureddy**
# Enhanced error handling in key functions:
- Added specific exception handling to 'summarize' and 'get_next_action_from_openai' functions for improved reliability and debugging.
- Introduced granular error handling for FileNotFound, Permission, Image, I/O, Base64 encoding, API request, and other potential exceptions.

### CODE REVIEW

**Comment by michaelhhogue** [comment]
@Prureddy This looks a lot better and comprehensively handles a lot of potential exceptions in ```get_next_action_from_openai``` with descriptive error messages. I'd like to see what @joshbickett thinks.

**Review by legendkartik45 — CHANGES_REQUESTED** [review]
Instead of adding additional lines for every exception, we can have only one line to capture all the exceptions.

**Review by legendkartik45 — CHANGES_REQUESTED** [review]
Lines 473 - 484 are redundant as 388-412.
We should try to optimize this such that we should not repeat code

**Comment by Prureddy** [comment]
@legendkartik45 Yess I can add thanks for your suggestion

**Comment by joshbickett** [comment]
It appears there may be an issue with the order of exceptions. @legendkartik45 suggestion may also help as well
```
Bad except clauses order (Exception is an ancestor class of Error)Pylint[E0701:bad-except-order](https://pylint.readthedocs.io/en/latest/user_guide/messages/error/bad-except-order.html)
```

Here's a ChatGPT thread about it: https://chat.openai.com/share/53fe5500-7fda-4935-ade9-5dd1fc94b2d6

**Comment by rohanarun** [comment]
Re-opening @michaelhhogue @joshbickett  are you an official contributor to this project? Could you comment on where the name Agent-1 came from? This appears to have blatantly ripped of the work of researchers working hard over a year.

Any open source contributors should consider that this firm raised millions and is scamming open source devs into stealing work for them. They never responded to our claims they stole this work, even down to the name agent-1, which is incredibly shameful if true and our attorneys would love to hear from an official contributor.

We will be publishing our solution open source as well, and here is Atlas-1, which we've been training for over a year and published last month: https://youtu.be/IQuBA7MvUas

What is Agent-1 and where did the name come from? It appears these guys blatantly ripped off our work and are now scamming open source devs into copying it for them.

**Review by alm0ra — COMMENTED** [review]
Why once you print and again you return ? 
Do you do any thing on returning? Why you didn't print on function result?

**Comment by joshbickett** [comment]
@Prureddy, let us know when you have an update on the questions. Would be great to merge this PR after a few corrections!

**Comment by joshbickett** [comment]
@Prureddy going to close this PR for the meantime. If you're able to implement some of the required updates for the error handling that'd be great. When your updates are ready feel free to reopen the PR, Thanks!

**Comment by Prureddy** [comment]
@joshbickett @alm0ra @legendkartik45 

Thank you for pointing out the concerns. I've optimized the code by consolidating exception handling into a single approach using a dictionary for better efficiency and readability. Redundant code segments have been refactored to avoid repetition, ensuring a streamlined structure.

Regarding the order of exceptions, I've organized them in specificity, which aligns with best practices for error handling in Python.

As for printing and returning, the code previously printed the error and returned an error message. I've adjusted the error handling function to return the error message directly, simplifying the structure and making it more cohesive. This change avoids unnecessary duplication between printing and returning.

The updates have significantly improved the code's clarity, maintainability, and adherence to best practices. Thank you for your feedback, which greatly contributed to these enhancements!tion 

image

**Pull request closed without merging**
