### PR TITLE
feat: add openai api base url

### LINKED ISSUE #9: Add support for LiteLLM to support API base change.
### 🚀 **Refactor the code** and use LiteLLM to support API base change.
🌐 As of now, GPT-4 Vision is *expensive to use* and GPT-4 usage is high.
Let consumers use their own API base by making the following change:

# Example:
```python
import openai

# Set your custom API base URL
openai.api_base = "http://myproxy-gpt.com/chatcompletions"
```

 📈 This change ensures that you will receive more users and encourage more testing.
🧪 People will start testing it more often, which will ultimately contribute to
*improving this product*. 🛠️

### PR DESCRIPTION
**Pull request by horw**
Add the ability to use the OPENAI_API_BASE_URL as an environment.

closes #9

### CODE REVIEW

**Comment by joshbickett** [comment]
@horw Curious to hear more about the value of including `client.base_url`. Either way I'll probably merge this, totally understand the `looping` change.

**Comment by coolrazor007** [comment]
@joshbickett the `client.base_url` allows you to point the openai library to another OpenAI API Compatible API.  For instance: LiteLLM
Meaning you can then host your own models with this.

**Comment by coolrazor007** [comment]
Also, this would be a game changer :)
https://github.com/haotian-liu/LLaVA/pull/834

**Comment by joshbickett** [comment]
Ok, great. Thanks for the input. I'll do some quick testing and then merge

**Comment by joshbickett** [comment]
@coolrazor007 @horw Merged 💥!

Also I did play around with LLaVA. From basic testing it didn't perform as well as GPT-4V, but definitely interested in integrating it as an easy to run model for the project! 

If someone could figure that out that'd be great. I think we'd need to find a company hosting LLaVA for inference that's easy to integrate with!

**Comment by coolrazor007** [comment]
> 
> 
> @coolrazor007 @horw Merged 💥!
> 
> 
> 
> Also I did play around with LLaVA. From basic testing it didn't perform as well as GPT-4V, but definitely interested in integrating it as an easy to run model for the project! 
> 
> 
> 
> If someone could figure that out that'd be great. I think we'd need to find a company hosting LLaVA for inference that's easy to integrate with!

Well as it happens I have compute available but I'll need help getting it working with Llava.  I have Google GCP TPUs available currently.  Let me know if you are interested in helping.  I'll reach out to Llava as well.

**Pull request merged**
