### PR TITLE
ADD: Issue templates added(pull request,bug,feature request).issue #120

### PR DESCRIPTION
**Pull request by Yash-1511**
This pull request introduces three new files under the .github folder - bug_report.md and feature_request.md and pull_request_template.md . These templates aim to standardize and enhance the issue reporting process within our repository. They provide a clear structure for submitting bug reports and feature requests, thereby improving clarity, ensuring completeness, and saving time for both contributors and maintainers. This contribution aligns with the suggestions and requirements outlined in issue #120.

### CODE REVIEW

**Comment by joshbickett** [comment]
Ok, I reviewed and it looks good.

**Comment by joshbickett** [comment]
@Yash-1511 let me know if you have thoughts on this, thanks

**Comment by Yash-1511** [comment]
@joshbickett We've set up two issue templates for our project: a bug report template and a feature request template. Contributors can also create a blank issue if their concern doesn't fit these categories. We're planning to add more templates and are transitioning to YAML syntax for easier issue filing. Issues from each template are automatically labeled appropriately. this label configuration is added in markdown file.

**Comment by joshbickett** [comment]
Oh ok, I didn't see the blank issue button

**Comment by Yash-1511** [comment]
There is no button. In bottom you can see create a blank issue link.

**Pull request merged**
